# Generated by Django 3.2.8 on 2021-10-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricerating',
            old_name='price_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='starrating',
            old_name='star_rating',
            new_name='rating',
        ),
    ]
